spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gm
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver

file_scanner:
  root_file_path: C:\SpringTasksRoot

errors_logger:
  file_path: C:\SpringTasksRootErr
  file_name: errors_log.txt
